#!/usr/bin/env python3
"""
Email notification script for weekly technical analysis reports.
Sends HTML visualizations via email to subscribers.
"""

import os
import sys
from pathlib import Path
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import smtplib

# Try to import sendgrid (optional - will use SMTP if not available)
try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail
    SENDGRID_AVAILABLE = True
except ImportError:
    SENDGRID_AVAILABLE = False
    print("Warning: SendGrid not available, will use SMTP")


def get_subscribers():
    """Get list of subscriber emails from environment variable."""
    subscribers_env = os.getenv("EMAIL_SUBSCRIBERS", "")
    if subscribers_env:
        return [email.strip() for email in subscribers_env.split(",") if email.strip()]
    
    # Default subscribers (fallback)
    return [
        "chemipoo@hotmail.com",
        "sobh.bekhair@outlook.com"
    ]


def generate_email_html():
    """Generate HTML email content from visualization files."""
    viz_dir = Path("visualizations_output")
    if not viz_dir.exists():
        return None
    
    html_parts = []
    html_parts.append("""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }
            .header { background-color: #4CAF50; color: white; padding: 20px; text-align: center; }
            .content { background-color: white; padding: 20px; margin: 20px 0; }
            .category { margin: 30px 0; border: 1px solid #ddd; padding: 15px; }
            .category h2 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }
            .footer { text-align: center; color: #666; padding: 20px; font-size: 12px; }
            a { color: #4CAF50; text-decoration: none; }
            a:hover { text-decoration: underline; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>📊 Weekly Technical Analysis Report</h1>
            <p>Generated: {date}</p>
        </div>
        <div class="content">
    """.format(date=datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")))
    
    # List all categories
    categories = {
        "cryptocurrencies": "Cryptocurrencies",
        "faang_hot_stocks": "FAANG / Hot Stocks",
        "quantum": "Quantum Computing",
        "miner_hpc": "Mining / HPC",
        "precious_metals": "Precious Metals",
        "index_etfs": "Index ETFs",
        "tech_stocks": "Tech Stocks"
    }
    
    for category_key, category_name in categories.items():
        html_file = viz_dir / f"{category_key}_scores.html"
        if html_file.exists():
            html_parts.append(f"""
            <div class="category">
                <h2>{category_name}</h2>
                <p>View full analysis: <a href="file://{html_file.absolute()}">Open {category_name} Report</a></p>
                <p><em>Note: Full interactive HTML file attached to this email.</em></p>
            </div>
            """)
    
    html_parts.append("""
        </div>
        <div class="footer">
            <p>This is an automated weekly report generated by Technical Analysis System.</p>
            <p>For questions or to unsubscribe, contact the administrator.</p>
        </div>
    </body>
    </html>
    """)
    
    return "".join(html_parts)


def send_via_sendgrid(subscribers, html_content):
    """Send email via SendGrid API."""
    if not SENDGRID_AVAILABLE:
        return False
    
    api_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("SENDGRID_FROM_EMAIL", "noreply@technical-analysis.com")
    
    if not api_key:
        print("Error: SENDGRID_API_KEY not set")
        return False
    
    sg = SendGridAPIClient(api_key)
    
    for subscriber in subscribers:
        message = Mail(
            from_email=from_email,
            to_emails=subscriber,
            subject=f"Weekly Technical Analysis Report - {datetime.now().strftime('%Y-%m-%d')}",
            html_content=html_content
        )
        
        # Attach HTML visualization files
        viz_dir = Path("visualizations_output")
        if viz_dir.exists():
            for html_file in viz_dir.glob("*.html"):
                if not html_file.name.startswith("test_"):
                    with open(html_file, 'rb') as f:
                        message.add_attachment(
                            f.read(),
                            filename=html_file.name,
                            mime_type="text/html"
                        )
        
        try:
            response = sg.send(message)
            print(f"✓ Sent report to {subscriber} (Status: {response.status_code})")
        except Exception as e:
            print(f"✗ Failed to send to {subscriber}: {e}")
            return False
    
    return True


def send_via_smtp(subscribers, html_content):
    """Send email via SMTP (Gmail or other SMTP server)."""
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")
    from_email = os.getenv("SMTP_FROM_EMAIL", smtp_user)
    
    if not smtp_user or not smtp_password:
        print("Error: SMTP_USER and SMTP_PASSWORD must be set")
        return False
    
    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(smtp_user, smtp_password)
        
        for subscriber in subscribers:
            msg = MIMEMultipart('alternative')
            msg['From'] = from_email
            msg['To'] = subscriber
            msg['Subject'] = f"Weekly Technical Analysis Report - {datetime.now().strftime('%Y-%m-%d')}"
            
            # Add HTML content
            html_part = MIMEText(html_content, 'html')
            msg.attach(html_part)
            
            # Attach HTML files
            viz_dir = Path("visualizations_output")
            if viz_dir.exists():
                for html_file in viz_dir.glob("*.html"):
                    if not html_file.name.startswith("test_"):
                        with open(html_file, 'rb') as f:
                            attachment = MIMEText(f.read(), 'html')
                            attachment.add_header(
                                'Content-Disposition',
                                'attachment',
                                filename=html_file.name
                            )
                            msg.attach(attachment)
            
            server.send_message(msg)
            print(f"✓ Sent report to {subscriber}")
        
        server.quit()
        return True
    except Exception as e:
        print(f"✗ SMTP error: {e}")
        return False


def main():
    """Main function to send weekly report."""
    print("=" * 60)
    print("Sending Weekly Technical Analysis Report")
    print("=" * 60)
    
    # Get subscribers
    subscribers = get_subscribers()
    if not subscribers:
        print("Error: No subscribers found")
        sys.exit(1)
    
    print(f"\nSubscribers: {', '.join(subscribers)}")
    
    # Generate HTML content
    print("\nGenerating email content...")
    html_content = generate_email_html()
    if not html_content:
        print("Error: Could not generate email content")
        sys.exit(1)
    
    # Try SendGrid first, fallback to SMTP
    print("\nSending emails...")
    success = False
    
    if SENDGRID_AVAILABLE and os.getenv("SENDGRID_API_KEY"):
        print("Using SendGrid API...")
        success = send_via_sendgrid(subscribers, html_content)
    elif os.getenv("SMTP_USER") and os.getenv("SMTP_PASSWORD"):
        print("Using SMTP...")
        success = send_via_smtp(subscribers, html_content)
    else:
        print("Error: No email service configured")
        print("Set either SENDGRID_API_KEY or SMTP_USER/SMTP_PASSWORD")
        sys.exit(1)
    
    if success:
        print(f"\n✓ Successfully sent reports to {len(subscribers)} subscriber(s)")
    else:
        print("\n✗ Failed to send reports")
        sys.exit(1)


if __name__ == "__main__":
    main()
